### ISSUE TITLE
LightNovelPub doesn't seem to be working

### ISSUE THREAD

**Issue by BreadGenie** [rajarsheechatterjee/lnreader-extensions#18]
The website seems to be loading fine but inside the app the output is `no results`. The search throws a `JSON Parse Error: Unexpected identifier "A"` error and also doesn't work.

Version: LNReader 1.0.18

**Comment by rajarsheechatterjee** [comment]
It has the same issue as FastNovel & MTLNovel. They work locally but return an empty array when deployed.

I don't know how to fix this so I'll just update the status to down.

![Screenshot 2021-05-16 071753](https://user-images.githubusercontent.com/57822170/118382869-28350b00-b617-11eb-8c63-9547b16c9042.png)

![Screenshot 2021-05-16 071820](https://user-images.githubusercontent.com/57822170/118382871-29fece80-b617-11eb-8987-4f23cd52b7a3.png)

**Comment by BreadGenie** [comment]
The same error still is shown while searching for novels.

**Comment by BreadGenie** [comment]
fixed in @724d13173eacb2085d0ba06f903fb58593849044

**Comment by BreadGenie** [comment]
Fixed in 724d13173eacb2085d0ba06f903fb58593849044
